### ISSUE TITLE
Tanstack Start - Usage in a Server Function

### ISSUE THREAD

**Issue by austinm911** [Nic13Gamer/better-upload#8]
https://tanstack.com/router/latest/docs/framework/react/start/server-functions#calling-server-functions-anywhere-else

Thanks for the library. Curious any guidance you might be able to share about using with Tanstack Start. 

Right now I'm just handling this in an API route as the provided components by the library seem to be tied to using API routes. It seems like Start users can use the `handleRequest` in a server function by grabbing the vinxi/http response and passing it through. Although i'm not totally sure if it's possible to use the provided components in a server function?

On a related note, I'm noticing that there is no `OnSuccess` callback provided by the `route` method. If a user wants to save file metadata in their database, wrapped in a transaction with the S3 upload (to be atomic), can this be achieved? I am wondering if there are cases when saving to database in the `onAfterSignedUrl` but you hit an error uploading to object storage, if you may end up with mis-matched data.

I can file another issue for this question

**Comment by Nic13Gamer** [comment]
Hey, @austinm911!

For your first question, you should use API routes, because the library needs the request to handle everything. Here is an example:

```ts
// routes/api/upload.ts
import { createAPIFileRoute } from '@tanstack/start/api'
import { handleRequest } from 'better-upload/server'

export const APIRoute = createAPIFileRoute('/upload')({
  GET: async ({ request }) => {
    return handleRequest(request, {
      // your router config...
    })
  },
})
```

I made this following the docs, if there are any issues please let me know.

As for the success callback, there isn't any because it is not possible without using events from the S3 service, which would complicate a lot and depends on which service you are using. In the future, I could implement a feature where the client calls the server and notifies that the upload is complete. If you really need this, you could implement your own logic or use UploadThing, which has this out of the box.

**Comment by austinm911** [comment]
> Hey, @austinm911!
> 
> For your first question, you should use API routes, because the library needs the request to handle everything. Here is an example:
> 
> ```ts
> // routes/api/upload.ts
> import { createAPIFileRoute } from '@tanstack/start/api'
> import { handleRequest } from 'better-upload/server'
> 
> export const APIRoute = createAPIFileRoute('/upload')({
>   GET: async ({ request }) => {
>     return handleRequest(request, {
>       // your router config...
>     })
>   },
> })
> ```
> 
> I made this following the docs, if there are any issues please let me know.
> 
> As for the success callback, there isn't any because it is not possible without using events from the S3 service, which would complicate a lot and depends on which service you are using. In the future, I could implement a feature where the client calls the server and notifies that the upload is complete. If you really need this, you could implement your own logic or use UploadThing, which has this out of the box. There is also a client-side callback when the upload is complete.

Thanks - what seems like a good solution for now without having to change much is just using a server function in the client side callback to do the data mutation.
